config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "users#index"
  get "/users/:id/dashboard" => "users#dashboard", as: "users_dashboard"
  resources :users do
  	resources :tasks
  	resources :categories
  end	



  post "/users/login" => "users#login", as: "users_login"
  delete "/users/log_out" => "users#logout", as: "users_logout"

  post "/users/:user_id/tasks/:id/edit" => "tasks#edit_update", as: "tasks_update" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	belongs_to :user
	has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
	require 'date'
	belongs_to :category
	enum status: { uncompleted: 0, completed: 1}
end

app/models/user.rb
class User < ApplicationRecord
	include BCrypt
	include ApplicationHelper
	require 'date'
	has_secure_password
	has_many :categories
	has_many :tasks , dependent: :destroy
	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :find_category, only: [:show] 

	def show
		@tasks = Task.where(category_id: params[:id]).order("start_date ASC")

	end 

	def find_category
		if @category = User.find_by(id: params[:id])
			return @user
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		user = User.find_by_email(params[:email])
   
     	if user && user.authenticate(params[:password])
       
	       	session[:user_id] = user.id
	       	flash[:notice] = "Signed in sucessfully"
	       	redirect_to '/'
	     else
	     
	     	flash[:notice] = "Email and password mismatched. Try again."
	     	redirect_to '/sign_in'
	    end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "Signed out sucessfully."
     	redirect_to '/'
	end	
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	include ApplicationHelper
	before_action :find_task, only: [:edit, :update, :edit_update]

	def create
		
		@task = current_user.tasks.new(task_params)
		
		if @task.save
			respond_to do |format|
			format.html {redirect_to "/users/#{current_user.id}"}
			format.js
			end
		else
			flash[:errors] = "Creation failed. Please try again."
			redirect_to "/users/#{@current_user.id}"
		end
	end

	def destroy
		@task = Task.find_by(id: params[:id])
		@task.destroy
		respond_to do |format|
		format.html { redirect_to "/users/#{current_user.id}" }
		format.js
		end
	end 

	def update
		if current_user.id == @task.user_id
			@task.update(task_params)
			flash[:success] = "ToDo updated sucessfully."
			redirect_to "/users/#{@task.user_id}/dashboard"
		else
			flash[:errors] = "Update failed!"
			redirect_to "/users/#{@task.user_id}/dashboard"
				
		end
	end


	def edit_update
		if current_user.id == @task.user_id

			@task.update(task_params)

			respond_to do |format|
			format.html { redirect_to "/users/#{current_user.id}" }
			format.js
			end
			# flash[:success] = "ToDo updated sucessfully."
			# redirect_to "/users/#{@task.user_id}"
		else
			flash[:errors] = "Update failed!"
			redirect_to "/users/#{@task.user_id}"
				
		end
	end
	

	private
	def task_params
		params.require(:task).permit(:title, :details, :start_date, :status, :category_id)
	end

	def find_task
		@task = Task.find_by(id: params[:id])
	end 

	def completed_task
		@tasks = Task.find_by(id: params[:id])
		@today_task = @tasks.where(start_date: DateTime.now)
		@incompleted = @today_task.where(status: 0)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include ApplicationHelper
	
	before_action :find_user, only: [:show, :edit, :update, :dashboard] 
	before_action :require_login, only: [:show, :edit]

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to "/users/#{@user.id}"
		else
			redirect_to root_path
		end	
	end	

	def login
		@user = User.find_by(email: params[:session][:email])
		if @user != nil && @user.authenticate(params[:session][:password])
			session[:user_id] = @user.id
			
			redirect_to "/users/#{@user.id}"

		else
			redirect_to root_path
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:info] = "Signed out sucessfully."
     	redirect_to '/'
	end

	def show
		@tasks = Task.where(user_id: params[:id]).order("start_date ASC")
		@today_task = @tasks.where(start_date: Date.today)
		@incompleted_task = @today_task.where(status: 0)
		@completed = @today_task.where(status: 1)
		@weekly_tasks = @tasks.where(start_date: (Date.today)+1..((Date.today)+7))

		@categories = @user.categories
	end 

	def dashboard
		@tasks = Task.where(user_id: params[:id]).order("start_date ASC")


	end

	private
	def user_params
		params.require(:user).permit(:name, :password, :email)
	end

	def find_user
		if @user = User.find_by(id: params[:id])
			return @user
		else
			redirect_to "/", :flash => { :errors => "Error!!!!"}	
		end
	end

	def require_login
		if !logged_in?
			redirect_to root_path
		end	
	end

	

end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
	  if session[:user_id]
	    @current_user ||= User.find_by_id(session[:user_id])
	  end
	end
	

	# Returns true if current_user exists, false otherwise
	def logged_in?
	  !current_user.nil?
	end
	
	
	# a convenient method to set the session to given user's id with the `:user_id` key
	def sign_in(user)
	  session[:user_id] = user.id
	end

	def flash_class(level)
	    case level
	        when "info" then "alert alert-info"
	        when "success" then "alert alert-success"
	        when "errors" then "alert alert-warning"
	        when "alert" then "alert alert-danger"
	    end
	end	
	
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/show.html.erb
<div class="table-container">
	<table class="task-list">
		<tr class="task-list-title">
			<th class="task-list-item col-lg-3">Title </th>
			<th class="task-list-item col-lg-3">Details</th>
		</tr>
		<% @tasks.each do |d| %>
		<tr class="task-list-details" id="done_<%= d.id %>">
		
			<td class="task-list-details col-lg-3"><%= d.title %></td>
			<td class="task-list-details col-lg-3"><%= d.details %></td>
			<%=form_for :task, url: tasks_update_path(d.user_id, d.id), id:"update_task", remote: true do |form| %>	

<!-- 			<td class="task-list-details col-lg-3" ><%# form.submit "Update", class: "text-field btn-submit form-control" %></td>
			<td class="task-list-details col-lg-1"><%# form.check_box :status, {:class => "edit_form"}, "completed", "uncompleted"%></td> -->

			<% end %>	
			

		</tr>
		<% end  %>

	</table>	
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
       
      </button>
      <a class="navbar-brand" href="/users/<%= "#{current_user.id}" %>">ToDo App</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     
        
      <ul class="nav navbar-nav navbar-right">
          <li class="nav navbar-nav navbar-right-item"><%= link_to 'Dashboard',users_dashboard_path(current_user.id), class: "modal-btn navbar-right-1" %></li>
          <li class="nav navbar-nav navbar-right-item"><%= link_to 'Log out',users_logout_path, method: :delete, class: "modal-btn navbar-right-1" %></li>
     
      </ul>
     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
  	<% flash.each do |key, value| %>
  	    <div class="<%= flash_class(key) %>">
  	          <%= value %>
  	    </div>
  	<% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_completed.html.erb
<tr class="task-list-details">

	<td class="task-list-details col-md-3"><%= completed.title%></td>
	<td class="task-list-details col-md-5"><%= completed.details %></td>
</tr>

app/views/tasks/_form.html.erb
<%= form_for Task.new, url: user_tasks_path(@user.id), id:"create_task", remote: true do |form| %>

<div class="text-field form-group">
    <%= form.select(:category_id, @user.categories.all.collect {|u| [u.category_title, u.id]}, :prompt => 'Select') %>
</div>


<div class="text-field form-group">
	<p>Date:
	<%= form.date_field :start_date, placeholder: 'Date', id:"start_date_form"%></p>
</div>
<div class="text-field form-group">
    <%= form.text_field :title, placeholder: 'Title', class: "form-control", id:"title_form"%>
</div>

<div class="text-field form-group">
    <%= form.text_area :details, :rows => 8, style: 'width:100%;', placeholder: 'Details', class: "form-control", id:"details_form"%>
</div>

<div class="form-group">
  <%= form.submit "Submit", class: "text-field btn-submit form-control" %>
</div> 

<% end %>

app/views/tasks/_task.html.erb
<tr class="task-list-details row" id="delete_<%= task.id %>">
	<td class="task-list-details col-lg-3"><%= task.start_date.strftime('%d %B %Y')%></td>
	<td class="task-list-details col-lg-3"><%= task.title %></td>
	<td class="task-list-details col-lg-5"><%= task.details %></td>
	<td class="task-list-details col-lg-5"><%= task.status %></td>
	<td class="task-list-details col-lg-1"><%= link_to "Edit", edit_user_task_path(task.user_id, task.id) %></td>
	<td class="task-list-details col-lg-1"><%= link_to "Delete", user_task_path(task.user_id, task.id), method: :delete, data: {confirm: "Do you want to delete this record?"}, remote:true %></td>
</tr>

app/views/tasks/check.js.erb
$('#completed_list').append('<%= j render(@completed) %>');
$('#done_<%= @incompleted.id %>').remove();

app/views/tasks/create.js.erb
$('#task_list').append('<%= j render(@task) %>');
$('#start_date_form').val('');
$('#title_form').val('');
$('#details_form').val('');

app/views/tasks/destroy.js.erb
$('#delete_<%= @task.id %>').remove();

app/views/tasks/edit.html.erb
<%= render partial: "/layouts/navbar" %>

<div class="container">
	<h2>Edit your ToDo HERE</h2>

	<%= form_for :task, url: user_task_path, method: :put do |form| %>
	<div class="text-field form-group">
		<p>Date:
		<%= form.date_field :start_date, placeholder: 'Date'%></p>
	</div>
	<div class="text-field form-group">
	    <%= form.text_field :title, placeholder: 'Title', class: "form-control"%>
	</div>

	<div class="text-field form-group">
	    <%= form.text_area :details, :rows => 8, style: 'width:100%;', placeholder: 'Details', class: "form-control"%>
	</div>

	<div class="form-group">
	  <%= form.submit "Update", class: "text-field btn-submit form-control" %>
	</div> 

	<% end %>
</div>	

app/views/tasks/edit_update.js.erb
$('#completed_list').append('<%= j render(partial: "tasks/completed", :locals => { :completed => @task})%>');
$('#done_<%= @task.id %>').remove();

app/views/users/dashboard.html.erb
<%= render partial: "/layouts/navbar" %>

<div class="container">
	<h3>Create a Todo</h3>
	<%= render partial: "/tasks/form" %> 
<hr>
<br>
	<div class="table-container">
		
		<table class="task-list" id="task_list">
			<tr class="task-list-title row">
				<th class="task-list-item col-lg-3">Date </th>
				<th class="task-list-item col-lg-3">Title </th>
				<th class="task-list-item col-lg-3">Details</th>
				<th class="task-list-item col-lg-3">Status</th>

			</tr>
		
			
			<%= render @tasks %>
			
			
		</table>	
	</div>	
<br>
</div>

app/views/users/index.html.erb
<div class="container">
    <h1>To Do List Application</h1>
    <div class="form-group">
    <h3>Sign up</h3>
    <%= form_for User.new, url: users_path do |form| %>
        <div class="text-field form-group">
            <%= form.text_field :name, placeholder: 'Name', class: "form-control"%>
        </div>

        <div class="text-field form-group">
            <%= form.text_field :email, placeholder: 'Email Address' , class: "form-control"%>
        </div> 

        <div class="text-field form-group">
            <%= form.password_field :password ,placeholder: 'Create a Password' , class: "form-control"%>
        </div>

        <div class="form-group">
          <%= form.submit "Create an account", class: "text-field btn-submit form-control" %>
        </div>

     <% end  %>  
    </div>      
    
    <br>
    
    <div class="form-group">
      <h3>Login</h3>     
      <%= form_for :session, url: users_login_path do |form| %>
        <div class="text-field form-group">
          <%= form.text_field :email, type: 'email', placeholder: "Email Address", class: "form-control" %>
        </div>

        <div class="password-field form-group">
          <%= form.password_field :password, placeholder: "Password", class: "form-control" %>
        </div>

        <div class="submit-field form-group" >
          <%= form.submit 'Log In', class: "form-control form-group-submit" %>
        </div>
              
        <% end %>
    </div>        
</div>

app/views/users/show.html.erb
<%= render partial: "/layouts/navbar" %>
<div class="container">

	<br>
	<h1>Hi, <%= @user.name %>.</h1>
	<span class="text-right">Date: <%= DateTime.now.strftime('%d %B %Y') %></span>
	
	<div class="row">
		<div class="col-md-6">
			<h3>Today's task</h3> 
			<div class="table-container">
				<table class="task-list">
					<tr class="task-list-title">
						<th class="task-list-item col-lg-3">Title </th>
						<th class="task-list-item col-lg-3">Details</th>
					</tr>
				<% if @incompleted_task.count == 0 %>
					<p>Do you have anything to do for today?</p>
				<% else  %>
					<% @incompleted_task.each do |d| %>
					<tr class="task-list-details" id="done_<%= d.id %>">
					
						<td class="task-list-details col-lg-3"><%= d.title %></td>
						<td class="task-list-details col-lg-3"><%= d.details %></td>
						<%=form_for :task, url: tasks_update_path(d.user_id, d.id), id:"update_task", remote: true do |form| %>	

						<td class="task-list-details col-lg-3" ><%= form.submit "Update", class: "text-field btn-submit form-control" %></td>
						<td class="task-list-details col-lg-1"><%= form.check_box :status, {:class => "edit_form"}, "completed", "uncompleted"%></td>

						<% end %>	
						

					</tr>
					<% end  %>
				<% end %>	
				</table>	
			</div>
		</div>
		<div class="col-md-6 tasks_complete">
			<h3>Tasks Completed</h3> 
			<div class="table-container">
				<table class="task-list" id="completed_list">
					<tr class="task-list-title">
						<th class="task-list-item col-lg-3">Title</th>
						<th class="task-list-item col-lg-3">Details</th>
					</tr>
				<% if @completed.count == 0 %>
					<p>No task completed</p>
				<% else  %>
					<% @completed.each do |c| %>
					<%= render partial:"tasks/completed", locals: { completed: c }%>
					<% end  %>
				<% end %>	
				</table>	
			</div>
		</div>	
	</div>
	<hr>

	<div>
		<h3>Categories</h3>

		<div>
			<% if @categories.count == 0  %>
				<p>Please create a todo list</p>
			<% else  %>
				<% @categories.each do |a| %>
				<%= link_to "#{a.category_title}", user_category_path(current_user.id, a.id)  %>

				<% end   %>
			<% end %>

		</div>
	</div>	

	<!-- <div>
		<h3>Coming Tasks</h3>
		<span><%# ((Date.today)+1).strftime('%d %B %Y')%> - <%# ((Date.today)+7).strftime('%d %B %Y')%></span> 
		<br>
		<br>
		<div class="table-container">
			<table class="task-list">
				<tr class="task-list-title row">
					<th class="task-list-item col-lg-3">Date </th>
					<th class="task-list-item col-lg-3">Title </th>
					<th class="task-list-item col-lg-5">Details</th>
					<th class="task-list-item col-lg-3">Status</th>
				</tr>

				<%# @weekly_tasks.each do |w| %>
				<tr class="task-list-details row">
				
					<td class="task-list-details col-lg-3"><%# w.start_date.strftime('%d %B %Y') %></td>
					<td class="task-list-details col-lg-3"><%# w.title %></td>
					<td class="task-list-details col-lg-5"><%# w.details %></td>
					<td class="task-list-details col-lg-3"><%# w.status %></td>
					

				</tr>
				<%# end  %>
				
			</table>	
		</div>
	</div>	 -->

	
	<br>
	<br>
	<%= link_to 'Edit or Add a new ToDo',users_dashboard_path(current_user.id), class: "add_todo text-field text-center btn-submit form-control" %>
	<br>
	<br>
</div>